### ISSUE TITLE
Multiple accounts yet it uses the same ip for all of them?

### ISSUE THREAD

**Issue by UngoogledUsers** [Apacelus/reddit-unbotter#1]
Using this with multiple accounts will still have reddit flag it as one account or a bot. So perhaps adding proxies or tor instances to each one would make it a perfect tool for the purpose.
I found there's a similar issue in your opinion changer repo. Once you do that from one ip Reddit flags it as fraudulent and won't count. And if it did, it'll get fixed in few hours.

Thank you for the repo.

**Comment by Apacelus** [comment]
The project is still in a very alpha phase, but the concept was to have the users log in under different user agents, so that reddit would think its a network with a lot of users(like a public wifi). 
Though, this is an interesting idea, I might add an option to let users connect from different tor instances but I see a lot of issues that would have to be accounted for + I would have to learn to do that.(So dont expect it too soon).
What I will certainly implement, is a time offset for the initial login, so that all the accounts wont login at the same time.

P.S: The accounts only login once, from then on they all use a seperate cookie to stay logged in.

**Comment by Apacelus** [comment]
About the opinion changer. The accounts used there did indeed all get flagged by reddit for vote manipulation, which was the inspiration for me to create this project, in order to prevent that from happening again.

**Comment by UngoogledUsers** [comment]
This is a brilliant idea. But i think reddit can still catch it. Since they'll be used to upvote/downvote the same thing and have a common IP will probably trigger it. But it might work if you don't want to use the accounts for that purpose and instead use them as normal non-shadowbanned new accounts.
I've got the idea of TOR/Proxies from reddit acc generators on here, for example:
https://github.com/redditacctgen01/Reddit-Account-Gen
https://github.com/ahaggard2013/Reddit-Account-Generator-and-Mass-Upvoter

I think doing multiple tor instances might be complex or tricky,but a proxy along with a proxy scraper from public lists or github repos will suffice and do a good job nonetheles.

The time offset is also a good idea, I think It also should be implemented on the upvote/downvote by perhaps few seconds in between and a minutes between each batch. As doing it instantly might also trigger detection.

I'm not that knowledgeable but i've made a script for reddit a while ago.I'll try to see if i can add to the repo.

Thanks again. Its a brilliant project idea and i've been searching for this exact thing today along with the creator.

**Comment by Apacelus** [comment]
@UngoogledUsers while the project is not finished yet, Ive added proxy support and a few other things.
